gisce/esios

esios/archives.py, esios/service.py, spec/archives_spec.py
Downloads liquicomun file from esios website
=> NEW liquicomun download

esios/archives.py, spec/archives_spec.py
Gets better liquicomun file from preferred ordered list
=> IMP Better liquicomun from predefined list

spec/archives_spec.py
=> FIX drops ESIOS_TOKEN

esios/archives.py, spec/archives_spec.py
When ordering, A6, C6, A7 and C7 prefixes fails
=> IMP Add C7, A7, C6 and A6 as prefixes

esios/indicators.py, requirements_dev.txt, spec/indicators_spec.py
PVPC indicator download
Adds indicators test
=> Imp pvpc indicators

esios/indicators.py, esios/service.py, spec/indicators_spec.py
- Get Morroco interconnection balance real time measurements.
=> Add Morroco link balance.

esios/archives.py, esios/indicators.py, spec/archives_spec.py, spec/indicators_spec.py
Add new esios indicators:
ID | Description | Model
-- | ----------- | -----
802 | Precio medio horario componente saldo P.O.14.6 contratación libre | mhpPO146BalanceFree
803 | Precio medio horario componente fallo nominación UPG contratación libre | mhpFalloNominacionUPGFree
1276 | PPrecio medio horario componente servicio interrumpibilidad contratación libre | mhpInterruptibilityServiceFree
1285 | Precio medio horario componente control factor potencia contratación libre | mhpPowerFactorControlFree
=> New free indicators

esios/indicators.py, spec/indicators_spec.py
Add new esios indicator **Incumplimiento energía de balance**:
ID | Description | Model
-- | ----------- | -----
1366 | Precio medio horario componente incumplimiento energía de balance contratación libre | mhpEnergyBalanceFree
=> New indicator mhpEnergyBalance (1366)

esios/indicators.py, spec/indicators_spec.py
New esios indicator (799):
**PRECIO MEDIO HORARIO COMPONENTE DESVÍOS MEDIDOS CONTRATACIÓN LIBRE**
Equivalent to liquicomun Grcosdnc 9th Column or column **I**
=> NEW indicator mhpMeasuredDeviationsFree

esios/indicators.py, requirements-dev.txt, spec/indicators_spec.py
Este nuevo indicador permite descargarse el precio de los excedentes en autoconsumos con compensacion simplificada
=> Add new indicator: PriceEnergiaExcedentariaAutoconsumCompensacioSimplificada (1739)

spec/indicators_spec.py
ESIOS has Changed Servicio interrumpibilidad  indicators descriptions
=> FIX Servicio Interrumpibilidad test descriptions

esios/parsers.py
=> FIX XSD path on any case

esios/indicators.py, spec/indicators_spec.py
- Added 961 indicator: `Precio medio anual componente mercado diario`
- Added test to ensure correct getting of 961 indicator.
=> Added ESIOS indicator 961

esios/indicators.py, spec/indicators_spec.py
Add the following `ESIOS` components:
- **808**: PRECIO MEDIO HORARIO COMPONENTE MERCADO INTRADIARIO
- **809**: PRECIO MEDIO HORARIO COMPONENTE RESTRICCIONES INTRADIARIO
- **812**: PRECIO MEDIO HORARIO COMPONENTE DESVÍOS MEDIDOS
- **814**: PRECIO MEDIO HORARIO COMPONENTE PAGO DE CAPACIDAD
- **816**: PRECIO MEDIO HORARIO COMPONENTE FALLO NOMINACIÓN UPG
- **1368**: PRECIO MEDIO HORARIO COMPONENTE INCUMPLIMIENTO ENERGÍA DE BALANCE
=> Add new ESIOS indicators

esios/indicators.py, spec/indicators_spec.py
Add the following `ESIOS` componentS:
- **1001**: TÉRMINO DE FACTURACIÓN DE ENERGÍA ACTIVA DEL PVPC 2.0TD
- **1006**: PERFILES DE CONSUMO A EFECTOS DE FACTURACIÓN DEL PVPC TARIFA 2.0TD
=> Add PricePVPC20TD indicator from ESIOS

esios/service.py
Add the following `ESIOS` component to base resources:
- **1006**: PERFILES DE CONSUMO A EFECTOS DE FACTURACIÓN DEL PVPC TARIFA 2.0TD
=> Add base resource indicator for PricePVPC20TD from ESIOS

esios/indicators.py, spec/indicators_spec.py
Add the following `ESIOS` components:
- **612**: `PRECIO MERCADO SPOT INTRADIARIO SESIÓN 1`
- **613**: `PRECIO MERCADO SPOT INTRADIARIO SESIÓN 2`
- **614**: `PRECIO MERCADO SPOT INTRADIARIO SESIÓN 3`
- **615**: `PRECIO MERCADO SPOT INTRADIARIO SESIÓN 4`
- **616**: `PRECIO MERCADO SPOT INTRADIARIO SESIÓN 5`
- **617**: `PRECIO MERCADO SPOT INTRADIARIO SESIÓN 6`
- **618**: `PRECIO MERCADO SPOT INTRADIARIO SESIÓN 7`
=> Add Spot Intra-daily price indicators

esios/indicators.py, spec/indicators_spec.py
Add the following `ESIOS` components:
- **686**: `PRECIO DE COBRO DESVÍOS A SUBIR`
- **687**: `PRECIO DE PAGO DESVÍOS A BAJAR`
- **726**: `COSTE DE LOS DESVÍOS MEDIDOS DE MAYOR PRODUCCIÓN`
- **727**: `COSTE DE LOS DESVÍOS MEDIDOS DE MENOR PRODUCCIÓN`
=> Se han añadido nuevos indicadores de ESIOS relacionados con la Representación a Mercado

README.rst, esios/data/urn-sios-ree-es-code-lists.xsd, esios/data/urn-sios-ree-es-core-cmpts.xsd, esios/data/urn-sios-ree-es-p48-1-0.xsd, esios/data/urn-sios-ree-es-p48cierre-1-0.xsd, esios/parsers.py, requirements.txt, spec/archives_spec.py, spec/parsers_spec.py
- Adaptaciones en las importaciones y en los tipos para mantener compatibilidad con `Python 2.7` y `Python 3.7`.
=>  Compatibilidad con Python3.7

spec/archives_spec.py
Add C3 on 3 months ago liquicomun test
=> IMP Add C3 on 3 months ago liquicomun test

esios/service.py
Añadir un User-Agent por defecto a las peticiones realizadas para evitar errores.
=> Definir User-Agent por defecto

esios/archives.py
- Añade la opción de descargar una versión específica de un componente.
- Él metodo `download` tiene un paramétro `maturity`.
=> Allow to download desired version for components

spec/indicators_spec.py
- Implementar tests para comprobar el correcto funcionamiento de los indicadores de generación y demanda.
- Completa https://github.com/gisce/esios/pull/59
=> Implementación de tests para indicadores de Generación y Demanda
